Importing the dataset and important libraries

In [71]:
import sys
assert sys.version_info >= (3, 7)
from packaging import version
import sklearn
assert version.parse(sklearn.__version__) >= version.parse("1.0.1")
import matplotlib.pyplot as plt
plt.rc('font', size=12)
plt.rc('axes', labelsize=14, titlesize=14)
plt.rc('legend', fontsize=12)
plt.rc('xtick', labelsize=10)
plt.rc('ytick', labelsize=10)
import numpy as np
np.random.seed(42)
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz #plot tree
!pip install ucimlrepo
!pip install pandas
import pandas as pd
from ucimlrepo import fetch_ucirepo

# fetch dataset

heart_disease = fetch_ucirepo(id=45)

# data (as pandas dataframes)

X = heart_disease.data.features

y = heart_disease.data.targets

Displaying the name of the columns, number of rows, number of columns, first 10 rows and last 10 rows

In [72]:
df = pd.DataFrame(heart_disease.data.features)
# Get column names, number of rows and columns
column_names = df.columns
rows, cols = df.shape

# Display first 10 and last 10 rows
first_10_rows = df.head(10)
last_10_rows = df.tail(10)


In [73]:
print("Column Names:", column_names)

Column Names: Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')


In [74]:
print("Number of Rows:", rows)

Number of Rows: 303


In [75]:
print("Number of Columns:", cols)

Number of Columns: 13


In [76]:
print('Shape:\n', df.shape)

Shape:
 (303, 13)


In [77]:
print("\nFirst 10 Rows:\n", first_10_rows)


First 10 Rows:
    age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   
5   56    1   2       120   236    0        0      178      0      0.8      1   
6   62    0   4       140   268    0        2      160      0      3.6      3   
7   57    0   4       120   354    0        0      163      1      0.6      1   
8   63    1   4       130   254    0        2      147      0      1.4      2   
9   53    1   4       140   203    1        2      155      1      3.1      3   

    ca  thal  
0  0.0   6.0  
1  3.0   3.0  
2  2.0   7.0  
3  0.0   3.0  
4  0.0   3.0  
5

In [78]:
print("\nLast 10 Rows:\n", last_10_rows)


Last 10 Rows:
      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
293   63    1   4       140   187    0        2      144      1      4.0   
294   63    0   4       124   197    0        0      136      1      0.0   
295   41    1   2       120   157    0        0      182      0      0.0   
296   59    1   4       164   176    1        2       90      0      1.0   
297   57    0   4       140   241    0        0      123      1      0.2   
298   45    1   1       110   264    0        0      132      0      1.2   
299   68    1   4       144   193    1        0      141      0      3.4   
300   57    1   4       130   131    0        0      115      1      1.2   
301   57    0   2       130   236    0        2      174      0      0.0   
302   38    1   3       138   175    0        0      173      0      0.0   

     slope   ca  thal  
293      1  2.0   7.0  
294      2  0.0   3.0  
295      1  0.0   3.0  
296      2  2.0   6.0  
297      2  0.0   7.0  
298

Display basic statistics of the dataset, such as the count, mean, standard deviation etc. Find any missing values

In [79]:
numerical_columns = df.select_dtypes(include=[np.number])  # Select numerical columns


# Check for missing values
missing_values = df.isnull().sum()
print("\nMissing Values:\n", missing_values)



Missing Values:
 age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
dtype: int64


In [80]:
print("Head:\n", df.head())

Head:
    age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

    ca  thal  
0  0.0   6.0  
1  3.0   3.0  
2  2.0   7.0  
3  0.0   3.0  
4  0.0   3.0  


In [81]:
print("Info:\n", df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        299 non-null    float64
 12  thal      301 non-null    float64
dtypes: float64(3), int64(10)
memory usage: 30.9 KB
Info:
 None


In [82]:
print("Describe:\n", df.describe())

Describe:
               age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.438944    0.679868    3.158416  131.689769  246.693069    0.148515   
std      9.038662    0.467299    0.960126   17.599748   51.776918    0.356198   
min     29.000000    0.000000    1.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    3.000000  120.000000  211.000000    0.000000   
50%     56.000000    1.000000    3.000000  130.000000  241.000000    0.000000   
75%     61.000000    1.000000    4.000000  140.000000  275.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  299.000000   
mean     0.990099  149.607261    0.326733    1.039604    1.600660    0.672241   
std      0.99497

Preprocessing the data by handling missing values and encoding categorical features.

In [83]:
df_encoded = pd.get_dummies(X, columns=['thal', 'cp']) # Encoding categorical features using one hot encoding
print("\nEncoded Dataframe:\n", df_encoded.head())
df.fillna(df.mean(), inplace=True) # handling missing values with the mean of each column

# Checking for missing values again
missing_values = df.isnull().sum()
print("\nMissing Values After Imputation:\n", missing_values)


Encoded Dataframe:
    age  sex  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1       145   233    1        2      150      0      2.3      3   
1   67    1       160   286    0        2      108      1      1.5      2   
2   67    1       120   229    0        2      129      1      2.6      2   
3   37    1       130   250    0        0      187      0      3.5      3   
4   41    0       130   204    0        2      172      0      1.4      1   

    ca  thal_3.0  thal_6.0  thal_7.0   cp_1   cp_2   cp_3   cp_4  
0  0.0     False      True     False   True  False  False  False  
1  3.0      True     False     False  False  False  False   True  
2  2.0     False     False      True  False  False  False   True  
3  0.0      True     False     False  False  False   True  False  
4  0.0      True     False     False  False   True  False  False  

Missing Values After Imputation:
 age         0
sex         0
cp          0
trestbps    0
chol        0
fbs      

Split the preprocessed data into training and testing sets (80% training, 20% testing)

In [84]:
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)


X_train shape: (242, 13)
y_train shape: (242, 1)
X_test shape: (61, 13)
y_test shape: (61, 1)


Implementing Random Forest Classifier algorithm to build a heart disease prediction model and training the model on the training data

In [86]:
#Running the model

model = RandomForestClassifier(
    n_estimators=500,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42
)
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
y_pred_quant = model.predict_proba(X_test)[:, 1] #storing predicted probabilites
y_pred = model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Checking Accuracy:

In [87]:
print("Training Accuracy :", model.score(X_train, y_train))
print("Testing Accuracy :", model.score(X_test, y_test))

Training Accuracy : 0.9421487603305785
Testing Accuracy : 0.4918032786885246


Cross Validation

In [88]:
from sklearn.model_selection import cross_val_score

# Perform cross-validation on the training set
scores = cross_val_score(model, X_train, y_train, cv=10)

# Print the cross-validation scores
print("Cross-validation scores:", scores)
print("Average cross-validation score:", scores.mean())

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 9 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/li

Cross-validation scores: [0.56       0.72       0.625      0.625      0.66666667 0.54166667
 0.54166667 0.66666667 0.58333333 0.58333333]
Average cross-validation score: 0.6113333333333333


Evaluating the model's performance using appropriate classification / regression metrics

In [89]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, confusion_matrix, accuracy_score, recall_score, precision_score, f1_score

# Calculate the mean absolute error
MAbE = mean_absolute_error(y_test, y_pred)
print("Mean absolute error:", MAbE)

Mean absolute error: 0.8032786885245902


In [90]:
# Calculate the mean squared error
MSqE = mean_squared_error(y_test, y_pred)
print("Mean squared error:", MSqE)

Mean squared error: 1.4918032786885247


In [91]:
# Calculate the confusion matrix
ConfMat = confusion_matrix(y_test, y_pred)
print("Confusion matrix:\n", ConfMat)

Confusion matrix:
 [[28  0  1  0  0]
 [ 6  1  4  1  0]
 [ 5  1  1  2  0]
 [ 1  4  2  0  0]
 [ 0  2  1  1  0]]


In [92]:
# Calculate the accuracy
Accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", Accuracy)

Accuracy: 0.4918032786885246


In [93]:
# Calculate the recall
Recall = recall_score(y_test, y_pred, average='weighted')
print("Recall:", Recall)

Recall: 0.4918032786885246


In [94]:
# Calculate the precision
Precision = precision_score(y_test, y_pred, average='weighted')
print("Precision:", Precision)

Precision: 0.37377049180327865


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [95]:
# Calculate the f-measure
FMeasure = f1_score(y_test, y_pred, average='weighted')
print("F-measure:", FMeasure)

F-measure: 0.4219054407222618


Fine-tuning the model by adjusting hyperparameters and trying different classification / regression algorithms.

In [96]:
# Fine-tuning the model using GridSearchCV

from sklearn.model_selection import GridSearchCV

# Define the grid of hyperparameters to search
param_grid = {
    'max_depth': [3, 5, 7, 9],
    'min_samples_leaf': [1, 2, 4],
    'min_samples_split': [2, 5, 10],
    'n_estimators': [100, 200, 500],
}

# Create the GridSearchCV object
grid_search = GridSearchCV(RandomForestClassifier(), param_grid, cv=5)

# Fit the grid search object to the data
grid_search.fit(X_train, y_train)

# Get the best set of hyperparameters
best_params = grid_search.best_params_

# Print the best parameters
print("Best Hyperparameters:", best_params)

# Train the model with the best hyperparameters
best_model = RandomForestClassifier(**best_params)
best_model.fit(X_train, y_train)

# Evaluate the best model on the test set
y_pred_best = best_model.predict(X_test)

# Calculate the accuracy of the best model
accuracy_best = accuracy_score(y_test, y_pred_best)

# Print the accuracy of the best model
print("Best Model Accuracy:", accuracy_best)


/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example usi

Best Hyperparameters: {'max_depth': 9, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 200}


/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Best Model Accuracy: 0.5245901639344263
